//------------------------------------------------------------------------------
// <auto-generated>
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martiscoin.Networks.X1.Properties {
    using System;
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Martiscoin.Networks.X1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string SpartacryptOpenCLMiner_opencl_device_info_h {
            get {
                return ResourceManager.GetString("SpartacryptOpenCLMiner.opencl_device_info.h", resourceCulture);
            }
        }
        
        internal static string SpartacryptOpenCLMiner_opencl_misc_h {
            get {
                return ResourceManager.GetString("SpartacryptOpenCLMiner.opencl_misc.h", resourceCulture);
            }
        }

        internal static string SpartacryptOpenCLMiner_opencl_sha2_common_h {
            get {
                return ResourceManager.GetString("SpartacryptOpenCLMiner.opencl_sha2_common.h", resourceCulture);
            }
        }
        
        internal static string SpartacryptOpenCLMiner_opencl_sha512_h {
            get {
                return ResourceManager.GetString("SpartacryptOpenCLMiner.opencl_sha512.h", resourceCulture);
            }
        }
        
        internal static string SpartacryptOpenCLMiner_sha512_miner_cl {
            get {
                return ResourceManager.GetString("SpartacryptOpenCLMiner.sha512_miner.cl", resourceCulture);
            }
        }
    }
}
